name: ygxqqx
# markdown: kramdown
markdown: makdown
highlighter: rouge

redcarpet:
 extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
 render_options:
author: ygxqqx
author_email: ygxqqx@163.com
safe: false
url: 
